### ISSUE TITLE
bugs / questions

### ISSUE THREAD

**Issue by drikssy** [Debond-Protocol/Debond-Token#9]
@yuliu-debond  we need to address the following queries. 

Debond-token
- [x] test mintAllocatedToken rigorously, the test doesn't take into consideration the allocated supply.
-  [x] Also about the mintCollateralized functionality, how it works,  whether there needs to be vesting etc.  
- how to balance DGOV for the allocation of investors 

VVIMP: 
- [x] explain the different mathematical formulas about the debond token functionality.
- [x] there is no contract logic that wants to recover the vesting.
- [x]  also the getLockedBalance, there is 5% of maxLocked supply that can be transferred, why is that fixed?
some external queries 
- [x] what supply will be stored if DGOV is minted in centralized exchange? thanks .

**Comment by dhruvmalik007** [comment]
- need to explain the lockable supply and collateralised supply .

**Comment by dhruvmalik007** [comment]
regarding the centralised-exchange: 
- we need to mint directly the tokens for the exchanges (without effecting the other supplies).

**Comment by dhruvmalik007** [comment]
regarding checking allocationSupply: 
- its checked in both debond-governance and token, thus we need to remove one implementation for gas efficiency.
